-- =====================================================================
-- Goals — Migração: procura do calendário em SEGUNDO PLANO.
-- Correr no SQL Editor do Supabase, DEPOIS de
-- schema.sql -> functions.sql -> policies.sql.
-- É IDEMPOTENTE: pode ser corrida mais que uma vez sem erro.
--
-- PORQUÊ ISTO EXISTE:
-- a procura do calendário com pesquisa Google passou a demorar MAIS do que um
-- pedido HTTP aguenta (visto nos logs: o Gemini com `google_search` neste
-- prompt leva mais de um minuto; o browser/iOS corta por volta dos 60s). O
-- resultado era o botão "Procurar jogos" a falhar sempre com "demorou
-- demasiado", por mais tempo que se lhe desse — o tecto não era nosso.
--
-- A solução é a mesma que a `sugerir-vinho` (WineSelection) já usa neste
-- projecto: a Edge Function cria aqui uma linha 'pendente', responde já com o
-- `id`, e continua o trabalho a sério com `EdgeRuntime.waitUntil` (sobrevive
-- ao pedido original terminar). A app faz polling a esta linha até o estado
-- mudar para 'concluido' ou 'erro'.
--
-- Isto também resolve o caso do telemóvel: com um só pedido pendurado, bloquear
-- o ecrã ou mudar de app matava a chamada a meio. Assim o trabalho continua no
-- servidor e a app volta a apanhá-lo.
--
-- QUEM ESCREVE:
--   · a Edge Function cria a linha com o JWT de quem carregou (a RLS abaixo é
--     que manda), e fecha-a depois com a service role — o trabalho em segundo
--     plano corre já sem o JWT original.
--
-- Só o admin mexe nisto: o botão do calendário é só dele (ver `is_admin()`).
-- =====================================================================

CREATE TABLE IF NOT EXISTS goals.calendario_analises (
  id         bigint GENERATED BY DEFAULT AS IDENTITY,
  criado_em  timestamptz NOT NULL DEFAULT now(),
  quem       text        NOT NULL DEFAULT '',   -- email de quem carregou
  epoca      text        NOT NULL DEFAULT '',
  estado     text        NOT NULL DEFAULT 'pendente',  -- 'pendente'|'concluido'|'erro'
  resultado  jsonb,                             -- a resposta completa, quando 'concluido'
  erro       text,                              -- mensagem legível, quando 'erro'
  CONSTRAINT calendario_analises_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS calendario_analises_criado_idx
  ON goals.calendario_analises (criado_em DESC);

ALTER TABLE goals.calendario_analises ENABLE ROW LEVEL SECURITY;

-- Ler: só o admin, e só as suas próprias linhas.
DROP POLICY IF EXISTS calendario_analises_sel ON goals.calendario_analises;
CREATE POLICY calendario_analises_sel ON goals.calendario_analises FOR SELECT
  USING (goals.is_admin());

-- Criar: só o admin. O `quem` é preenchido pela função com o email do JWT.
DROP POLICY IF EXISTS calendario_analises_ins ON goals.calendario_analises;
CREATE POLICY calendario_analises_ins ON goals.calendario_analises FOR INSERT
  WITH CHECK (goals.is_admin());

-- Apagar: só o admin — serve para não deixar isto crescer para sempre.
DROP POLICY IF EXISTS calendario_analises_del ON goals.calendario_analises;
CREATE POLICY calendario_analises_del ON goals.calendario_analises FOR DELETE
  USING (goals.is_admin());

-- Nota: não há policy de UPDATE de propósito. Quem fecha a linha é a Edge
-- Function com a SERVICE ROLE (que passa por cima da RLS), porque nessa altura
-- o JWT de quem carregou já não existe. Ninguém mais tem de poder escrever aqui.

GRANT SELECT, INSERT, DELETE ON goals.calendario_analises TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA goals TO authenticated;
