-- =====================================================================
-- Goals — Migração: outbox de notificações push + retry (pg_cron).
-- Correr no SQL Editor do Supabase, DEPOIS de push-subscriptions.sql.
-- É IDEMPOTENTE (pode ser corrida mais que uma vez sem erro).
--
-- PORQUÊ: `push-notificar-goals` é fire-and-forget — se o pedido REST
-- interno (checar `allowed_users`, checar `push_subscriptions`) apanhar um
-- dos picos de "Thread killed by timeout manager" do PostgREST deste
-- projeto partilhado (FestasBV/SplitBill/Goals) — não é raro, acontece
-- dezenas de vezes por hora — a notificação perdia-se sem ninguém dar por
-- isso (foi o que aconteceu a um pedido de pagamento da Barrona a
-- 2026-08-15). Esta tabela é o registo do que foi pedido e se chegou a
-- sair; o que ficar por enviar é reencaminhado pela `push-retry-goals`,
-- chamada de 30 em 30 min por um pg_cron.
--
-- Só a service role (as duas Edge Functions) mexe nesta tabela — RLS fica
-- ligado sem nenhuma policy (nega tudo a anon/authenticated por omissão),
-- o browser nunca lhe toca.
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;
-- supabase_vault já vem ativa por omissão neste projeto (partilhada com o
-- FestasBV) — guarda a service_role key que o pg_cron usa para chamar a
-- Edge Function (ver passo manual no README, não fica em texto aqui).

CREATE TABLE IF NOT EXISTS goals.push_notificacoes (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo             text NOT NULL,             -- 'pedido_acesso' | 'pagamento_declarado' | 'pagamento_aprovado' | 'resultado_jogo'
  audiencia        text NOT NULL,             -- 'admin' | 'todos' | 'amigo' (amigo: emailAlvo dentro do payload)
  payload          jsonb NOT NULL,            -- {title, body, url} do Web Push
  tentativas       int NOT NULL DEFAULT 0,
  enviado          boolean NOT NULL DEFAULT false,
  criado_em        timestamptz NOT NULL DEFAULT now(),
  ultima_tentativa timestamptz,
  enviado_em       timestamptz
);

CREATE INDEX IF NOT EXISTS push_notificacoes_pendentes_idx
  ON goals.push_notificacoes (criado_em)
  WHERE enviado = false;

ALTER TABLE goals.push_notificacoes ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------
-- Agenda o varrimento de 30 em 30 min. Depende do passo manual (ver
-- README): criar em Project Settings → Vault um secret chamado
-- `service_role_key` com o valor da tua service_role key. Sem ele, o
-- Authorization sai vazio e a push-retry-goals responde sempre 403 —
-- tolerante (nada rebenta), só fica sem efeito até criares o secret.
-- Podes correr este bloco outra vez a seguir a criar o secret, ou só
-- esperar pela próxima vez que este ficheiro for aplicado do zero.
-- ---------------------------------------------------------------------

SELECT cron.unschedule('goals-push-retry')
WHERE EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'goals-push-retry');

SELECT cron.schedule(
  'goals-push-retry',
  '*/30 * * * *',
  $$
  SELECT net.http_post(
    url := 'https://gjweqwfbnkgnibhajldc.supabase.co/functions/v1/push-retry-goals',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'service_role_key')
    ),
    body := '{}'::jsonb
  );
  $$
);
-- =====================================================================
