-- =====================================================================
-- Goals — Schema DDL (schema `goals`)
-- Mesmo projeto Supabase do FestasBV (diogoandrefsilva-personalapps-database),
-- schema isolado — não mexe em nada de `festasbv`.
-- Correr no SQL Editor do Supabase, por esta ordem: schema.sql -> functions.sql
-- -> policies.sql. Ver db/README.md para os passos manuais (expor o schema na
-- API, redirect URLs, template de email).
--
-- NOTA sobre IDs: ao contrário do núcleo do FestasBV (que reescreve os filhos
-- de um evento em bloco e por isso controla os ids à mão), aqui cada mutação
-- é um POST/PATCH/DELETE de uma linha de cada vez — por isso os `id` são
-- `GENERATED BY DEFAULT AS IDENTITY` (mesma convenção das tabelas add-on do
-- FestasBV como `categorias`/`filhos`): a app lê o id de volta da resposta
-- do POST (`Prefer: return=representation`), nunca o inventa.
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS goals;

-- ---------------------------------------------------------------------
-- Controlo de acesso
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS goals.allowed_users (
  email      text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT allowed_users_pkey PRIMARY KEY (email)
);

CREATE TABLE IF NOT EXISTS goals.access_requests (
  email        text NOT NULL,
  requested_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT access_requests_pkey PRIMARY KEY (email)
);

-- Liga o login (email) ao NOME de um amigo. O nome é a identidade estável —
-- um id de `amigos` é por época (cada época tem a sua cópia); o mesmo nome
-- é o que atravessa as épocas todas, exatamente como o FestasBV liga
-- user_amigos.amigo ao nome em `membros` (que também é por evento).
CREATE TABLE IF NOT EXISTS goals.user_amigos (
  email      text NOT NULL,
  amigo      text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_amigos_pkey PRIMARY KEY (email)
);

-- Configuração global (key-value). Chave atual: 'valor_por_golo'
-- (era dbFull.config.valorPorGolo — global a todas as épocas, não por época).
CREATE TABLE IF NOT EXISTS goals.config (
  chave text NOT NULL,
  valor text NOT NULL,
  CONSTRAINT config_pkey PRIMARY KEY (chave)
);

INSERT INTO goals.config (chave, valor)
VALUES ('valor_por_golo', '1')
ON CONFLICT (chave) DO NOTHING;

-- ---------------------------------------------------------------------
-- Núcleo: épocas e tudo o que delas depende (ON DELETE CASCADE)
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS goals.epocas (
  nome                 text NOT NULL,             -- ex: '2025/26'
  criado_em            timestamptz NOT NULL DEFAULT now(),
  pote_holder_amigo_id bigint,                     -- FK acrescentada abaixo (depende de `amigos`)
  CONSTRAINT epocas_pkey PRIMARY KEY (nome)
);

CREATE TABLE IF NOT EXISTS goals.amigos (
  id         bigint GENERATED BY DEFAULT AS IDENTITY,
  epoca_nome text   NOT NULL REFERENCES goals.epocas (nome) ON DELETE CASCADE,
  nome       text   NOT NULL,
  cor        text   NOT NULL DEFAULT '#045c40',
  ordem      integer NOT NULL DEFAULT 0,
  CONSTRAINT amigos_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS amigos_epoca_idx ON goals.amigos (epoca_nome);

-- Só agora a FK de epocas.pote_holder_amigo_id pode ser criada (depende de `amigos`)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'epocas_pote_holder_fkey'
  ) THEN
    ALTER TABLE goals.epocas
      ADD CONSTRAINT epocas_pote_holder_fkey
      FOREIGN KEY (pote_holder_amigo_id) REFERENCES goals.amigos (id) ON DELETE SET NULL;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS goals.jogos (
  id          bigint GENERATED BY DEFAULT AS IDENTITY,
  epoca_nome  text   NOT NULL REFERENCES goals.epocas (nome) ON DELETE CASCADE,
  data        date   NOT NULL,
  adversario  text   NOT NULL,
  competicao  text   NOT NULL DEFAULT '',
  jornada     text   NOT NULL DEFAULT '',
  local       text,                                -- 'Casa' | 'Fora' | 'Neutro'
  golos       integer,                              -- null = jogo futuro, sem resultado
  resultado   text,                                 -- ex: '2-1', opcional
  CONSTRAINT jogos_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS jogos_epoca_idx ON goals.jogos (epoca_nome);

CREATE TABLE IF NOT EXISTS goals.pagos_jogo (
  jogo_id  bigint NOT NULL REFERENCES goals.jogos  (id) ON DELETE CASCADE,
  amigo_id bigint NOT NULL REFERENCES goals.amigos (id) ON DELETE CASCADE,
  CONSTRAINT pagos_jogo_pkey PRIMARY KEY (jogo_id, amigo_id)
);

CREATE TABLE IF NOT EXISTS goals.estouros (
  id         bigint GENERATED BY DEFAULT AS IDENTITY,
  epoca_nome text   NOT NULL REFERENCES goals.epocas (nome) ON DELETE CASCADE,
  nome       text   NOT NULL DEFAULT 'Evento',
  data       date,
  valor      numeric(10,2) NOT NULL DEFAULT 0,
  pago_por   bigint REFERENCES goals.amigos (id) ON DELETE SET NULL,
  CONSTRAINT estouros_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS estouros_epoca_idx ON goals.estouros (epoca_nome);

CREATE TABLE IF NOT EXISTS goals.estouro_participantes (
  estouro_id bigint NOT NULL REFERENCES goals.estouros (id) ON DELETE CASCADE,
  amigo_id   bigint NOT NULL REFERENCES goals.amigos   (id) ON DELETE CASCADE,
  CONSTRAINT estouro_participantes_pkey PRIMARY KEY (estouro_id, amigo_id)
);

-- Presença = amigo acertado (toggleEstouroPago). Chave só no amigo_id: a
-- época já está implícita no amigo (amigos são por época).
CREATE TABLE IF NOT EXISTS goals.estouro_pagos (
  amigo_id bigint NOT NULL REFERENCES goals.amigos (id) ON DELETE CASCADE,
  CONSTRAINT estouro_pagos_pkey PRIMARY KEY (amigo_id)
);

CREATE TABLE IF NOT EXISTS goals.creditos_extra (
  id         bigint GENERATED BY DEFAULT AS IDENTITY,
  epoca_nome text   NOT NULL REFERENCES goals.epocas (nome) ON DELETE CASCADE,
  valor      numeric(10,2) NOT NULL DEFAULT 0,
  nome       text NOT NULL DEFAULT '',   -- descrição do crédito (ex: "Sobra da época anterior")
  data       date,
  CONSTRAINT creditos_extra_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS creditos_extra_epoca_idx ON goals.creditos_extra (epoca_nome);

-- ---------------------------------------------------------------------
-- Pedidos de pagamento à espera de validação (feature 3)
-- "Já paguei os jogos A, B, D" — o admin aprova ou rejeita. Enquanto
-- pendente, NÃO entra em pagos_jogo: não é dinheiro, é só um aviso.
-- Mesmo padrão do festasbv.pagamentos_pendentes.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS goals.pedidos_pagamento (
  id               bigint GENERATED BY DEFAULT AS IDENTITY,
  epoca_nome       text   NOT NULL REFERENCES goals.epocas (nome) ON DELETE CASCADE,
  amigo_id         bigint NOT NULL REFERENCES goals.amigos (id)  ON DELETE CASCADE,
  jogo_ids         bigint[] NOT NULL,
  valor            numeric(10,2) NOT NULL DEFAULT 0,   -- soma calculada no cliente, informativo
  nota             text NOT NULL DEFAULT '',
  estado           text NOT NULL DEFAULT 'pendente',   -- 'pendente' | 'aprovado' | 'rejeitado'
  criado_por_email text NOT NULL DEFAULT '',
  criado_em        timestamptz NOT NULL DEFAULT now(),
  decidido_por     text,
  decidido_em      timestamptz,
  motivo           text,
  CONSTRAINT pedidos_pagamento_pkey PRIMARY KEY (id),
  CONSTRAINT pedidos_pagamento_estado_chk
    CHECK (estado IN ('pendente','aprovado','rejeitado')),
  -- cardinality(), não array_length(): um array VAZIO dá array_length()=NULL
  -- (não 0), e "NULL > 0" passa sempre num CHECK — deixava entrar {} calado.
  CONSTRAINT pedidos_pagamento_jogos_chk CHECK (cardinality(jogo_ids) > 0)
);
CREATE INDEX IF NOT EXISTS pedidos_pagamento_epoca_idx ON goals.pedidos_pagamento (epoca_nome);
CREATE INDEX IF NOT EXISTS pedidos_pagamento_amigo_idx ON goals.pedidos_pagamento (amigo_id);

-- ---------------------------------------------------------------------
-- GRANTs (sem isto: HTTP 403 / 42501 em tudo)
-- ---------------------------------------------------------------------
GRANT USAGE ON SCHEMA goals TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA goals TO anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA goals GRANT ALL ON TABLES TO anon, authenticated;

-- ---------------------------------------------------------------------
-- RLS (as policies ficam em policies.sql, depois de functions.sql)
-- ---------------------------------------------------------------------
ALTER TABLE goals.allowed_users        ENABLE ROW LEVEL SECURITY;
ALTER TABLE goals.access_requests      ENABLE ROW LEVEL SECURITY;
ALTER TABLE goals.user_amigos          ENABLE ROW LEVEL SECURITY;
ALTER TABLE goals.config               ENABLE ROW LEVEL SECURITY;
ALTER TABLE goals.epocas               ENABLE ROW LEVEL SECURITY;
ALTER TABLE goals.amigos               ENABLE ROW LEVEL SECURITY;
ALTER TABLE goals.jogos                ENABLE ROW LEVEL SECURITY;
ALTER TABLE goals.pagos_jogo           ENABLE ROW LEVEL SECURITY;
ALTER TABLE goals.estouros             ENABLE ROW LEVEL SECURITY;
ALTER TABLE goals.estouro_participantes ENABLE ROW LEVEL SECURITY;
ALTER TABLE goals.estouro_pagos        ENABLE ROW LEVEL SECURITY;
ALTER TABLE goals.creditos_extra       ENABLE ROW LEVEL SECURITY;
ALTER TABLE goals.pedidos_pagamento    ENABLE ROW LEVEL SECURITY;
