-- =====================================================================
-- Goals — Migração: registo de diagnóstico da sincronização do calendário.
-- Correr no SQL Editor do Supabase, DEPOIS de
-- schema.sql -> functions.sql -> policies.sql.
-- É IDEMPOTENTE: pode ser corrida mais que uma vez sem erro.
--
-- PORQUÊ ISTO EXISTE:
-- o botão "Procurar jogos" atravessa três sítios (browser → Edge Function
-- `calendario-sporting` → Gemini) e, quando não funciona, um toast que
-- desaparece em 3 segundos não chega para saber ONDE partiu. Cada tentativa
-- deixa aqui uma linha, e é isto que se lê para despistar sem depender de
-- apanhar o erro no ecrã no momento certo.
--
-- QUEM ESCREVE:
--   · a app (Goals), com o login do admin: uma linha 'pedido' antes de chamar
--     e uma 'erro' se a chamada falhar. É o que apanha o caso "nem sequer
--     saiu do browser" (rede, CORS, função não publicada).
--   · a Edge Function, com a service role (bypassa RLS): uma linha 'ok' ou
--     'erro' com o modelo usado, se houve pesquisa Google e quantos jogos
--     saíram. É o que apanha o que se passa do lado do Gemini.
--     A MESMA função serve o SplitBill — daí o campo `app`, que diz de qual
--     das duas veio o pedido. O SplitBill não escreve aqui directamente (não
--     tem acesso ao schema `goals`); as chamadas dele aparecem na mesma pela
--     mão da função.
--
-- A tabela é propositadamente burra: `detalhe jsonb` leva o que interessar em
-- cada momento, sem obrigar a migrações novas de cada vez que se quer registar
-- mais um campo.
-- =====================================================================

CREATE TABLE IF NOT EXISTS goals.sync_log (
  id         bigint GENERATED BY DEFAULT AS IDENTITY,
  criado_em  timestamptz NOT NULL DEFAULT now(),
  origem     text        NOT NULL,                    -- 'app' | 'function'
  app        text        NOT NULL DEFAULT 'goals',    -- 'goals' | 'splitbill'
  acao       text        NOT NULL DEFAULT 'calendario',
  estado     text        NOT NULL,                    -- 'pedido' | 'ok' | 'erro'
  quem       text,                                    -- email de quem carregou
  detalhe    jsonb       NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT sync_log_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS sync_log_criado_idx ON goals.sync_log (criado_em DESC);

ALTER TABLE goals.sync_log ENABLE ROW LEVEL SECURITY;

-- Ler: só o admin (é diagnóstico, não é dado de utilizador).
DROP POLICY IF EXISTS sync_log_sel ON goals.sync_log;
CREATE POLICY sync_log_sel ON goals.sync_log FOR SELECT
  USING (goals.is_admin());

-- Escrever: qualquer conta com acesso. De propósito mais largo que a leitura —
-- se um dia o botão aparecer a quem não devia, ou o `is_admin()` falhar, quero
-- que a tentativa FIQUE REGISTADA em vez de desaparecer sem rasto.
DROP POLICY IF EXISTS sync_log_ins ON goals.sync_log;
CREATE POLICY sync_log_ins ON goals.sync_log FOR INSERT
  WITH CHECK (goals.is_allowed());

-- Limpeza: só o admin, e serve para não deixar isto crescer para sempre.
DROP POLICY IF EXISTS sync_log_del ON goals.sync_log;
CREATE POLICY sync_log_del ON goals.sync_log FOR DELETE
  USING (goals.is_admin());

GRANT SELECT, INSERT, DELETE ON goals.sync_log TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA goals TO authenticated;
